; This should be copied to magpie.config.ini

[db]
host     = 127.0.0.1
port     = 5432
dbname   = magpie_db
username = magpie_user
password = magpie_paassword

[security]
; IP address allowed to use ?debug=1 (Krumo dumps). Loopback is always allowed.
admin_ip = 67.22.241.17
